# Generated by Django 4.0.3 on 2022-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWarehouseAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse_stocks',
            fields=[
                ('Mfd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitsInStock', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Warehouse_stock',
        ),
    ]
